### ISSUE TITLE
Fix issues with 1d/3d intersections and 1d/1d 

### ISSUE THREAD

**Issue by luca-heltai** [luca-heltai/fsi-suite#24]
Currently we have the following lines in our parmoonolith interface, because 1d/1d and 1d/3d are not implemented.

https://github.com/luca-heltai/fsi-suite/pull/22/commits/a6e464a9315e274046aa7fcf53ae100186101341#diff-9f9f20c70ac14ef0e88f022634cc6beb461d585cce08ddd32b5067640753dcc1R395-R396

we should either implement these manually (they are trivial to implement in 1d), or upstream the implementation in parmoonolith.

**Comment by fdrmrc** [comment]
Fixed upstream https://www.dealii.org/developer/doxygen/deal.II/namespaceCGALWrappers.html#a8a84521982f4804b2e2d8268e90dc317
